/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package angsuran.view;

import angsuran.controller.BaController;
import angsuran.controller.ImportController;
import angsuran.helper.HelperUmum;
import angsuran.helper.TombolCrud;
import angsuran.helper.TombolGeneral;
import angsuran.listener.Confirm;
import angsuran.model.Ba;
import com.stripbandunk.jwidget.JPagination;
import com.stripbandunk.jwidget.event.PaginationEvent;
import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author User
 */


public class BAFrame extends javax.swing.JFrame implements Confirm{
    
    private BaController c;
    
    private Ba ba = new Ba();

    public Ba getBa() {
        return ba;
    }

    public void setBa(Ba ba) {
        this.ba = ba;
    }
    
    //========================================

    public JTextField getCariba() {
        return cariba;
    }

    public JTextField getHnotifikasi() {
        return hnotifikasi;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTextField getNamabu() {
        return namabu;
    }

    public JTextField getNoba() {
        return noba;
    }

    public JTextField getEmail() {
        return email;
    }
    public JTextField getNoentitas() {
        return noentitas;
    }

    public JPagination getPaginba() {
        return paginba;
    }

    public JTable getTableba() {
        return tableba;
    }

    public JTextField getTahapcicilan() {
        return tahapcicilan;
    }

    public JDateChooser getTanggalba() {
        return tanggalba;
    }

    public JTextField getTotaltunggakan() {
        return totaltunggakan;
    }

    public JComboBox<String> getKategori() {
        return kategori;
    }
    
    

    
    public BAFrame() {
        initComponents();
        new TombolCrud(baru);
        new TombolCrud(simpan);
        new TombolCrud(update);
        new TombolCrud(delete);
        new TombolCrud(reset);
        new TombolCrud(btncari);
        new TombolGeneral(tombolimport);
        new TombolGeneral(keluar);
        HelperUmum.setTextfieldHanyaAngka(tahapcicilan);
        HelperUmum.formatInputanTextfield(totaltunggakan);
        HelperUmum.setUpResolution(this);
        HelperUmum.setlogoframe(this);
        c = new BaController();
        c.loadkategori(this);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPanelDasar1 = new angsuran.helper.DeskPanelDasar();
        logoBpjs1 = new angsuran.helper.LogoBpjs();
        transparant1 = new angsuran.helper.Transparant();
        namabu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        noentitas = new javax.swing.JTextField();
        noba = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tanggalba = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        totaltunggakan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tahapcicilan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hnotifikasi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        transparant2 = new angsuran.helper.Transparant();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableba = new javax.swing.JTable();
        paginba = new com.stripbandunk.jwidget.JPagination();
        cariba = new javax.swing.JTextField();
        kategori = new javax.swing.JComboBox<>();
        btncari = new javax.swing.JButton();
        tombolimport = new javax.swing.JButton();
        baru = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        org.jdesktop.layout.GroupLayout logoBpjs1Layout = new org.jdesktop.layout.GroupLayout(logoBpjs1);
        logoBpjs1.setLayout(logoBpjs1Layout);
        logoBpjs1Layout.setHorizontalGroup(
            logoBpjs1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 275, Short.MAX_VALUE)
        );
        logoBpjs1Layout.setVerticalGroup(
            logoBpjs1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 50, Short.MAX_VALUE)
        );

        transparant1.setBackground(new java.awt.Color(41, 22, 111));
        transparant1.setForeground(new java.awt.Color(41, 22, 111));
        transparant1.setToolTipText("");

        namabu.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        namabu.setForeground(new java.awt.Color(0, 0, 51));
        namabu.setBorder(null);
        namabu.setCaretColor(new java.awt.Color(0, 0, 51));
        namabu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namabuActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("NAMA BU");

        jLabel3.setBackground(new java.awt.Color(0, 0, 51));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("NO ENTITAS");

        noentitas.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        noentitas.setForeground(new java.awt.Color(0, 0, 51));
        noentitas.setBorder(null);
        noentitas.setCaretColor(new java.awt.Color(0, 0, 51));
        noentitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noentitasActionPerformed(evt);
            }
        });

        noba.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        noba.setForeground(new java.awt.Color(0, 0, 51));
        noba.setBorder(null);
        noba.setCaretColor(new java.awt.Color(0, 0, 51));
        noba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nobaActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("NO BA");

        jLabel5.setBackground(new java.awt.Color(0, 0, 51));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("TANGGAL BA");

        totaltunggakan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        totaltunggakan.setForeground(new java.awt.Color(0, 0, 51));
        totaltunggakan.setBorder(null);
        totaltunggakan.setCaretColor(new java.awt.Color(0, 0, 51));
        totaltunggakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltunggakanActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 51));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("TOTAL TUNGGAKAN");

        jLabel7.setBackground(new java.awt.Color(0, 0, 51));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("TAHAP CICILAN");

        tahapcicilan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        tahapcicilan.setForeground(new java.awt.Color(0, 0, 51));
        tahapcicilan.setBorder(null);
        tahapcicilan.setCaretColor(new java.awt.Color(0, 0, 51));
        tahapcicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahapcicilanActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 51));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("H-NOTIFIKASI");

        hnotifikasi.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        hnotifikasi.setForeground(new java.awt.Color(0, 0, 51));
        hnotifikasi.setBorder(null);
        hnotifikasi.setCaretColor(new java.awt.Color(0, 0, 51));

        jLabel11.setBackground(new java.awt.Color(0, 0, 51));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("EMAIL");

        email.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 51));
        email.setBorder(null);
        email.setCaretColor(new java.awt.Color(0, 0, 51));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout transparant1Layout = new org.jdesktop.layout.GroupLayout(transparant1);
        transparant1.setLayout(transparant1Layout);
        transparant1Layout.setHorizontalGroup(
            transparant1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(transparant1Layout.createSequentialGroup()
                .addContainerGap()
                .add(transparant1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(transparant1Layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(noentitas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, transparant1Layout.createSequentialGroup()
                        .add(transparant1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(jLabel7)
                            .add(jLabel9)
                            .add(jLabel11))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(transparant1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(noba)
                            .add(totaltunggakan)
                            .add(tahapcicilan)
                            .add(hnotifikasi)
                            .add(tanggalba, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(email)))
                    .add(transparant1Layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(namabu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(133, 133, 133))
        );
        transparant1Layout.setVerticalGroup(
            transparant1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(transparant1Layout.createSequentialGroup()
                .addContainerGap()
                .add(transparant1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(namabu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(transparant1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(noentitas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(transparant1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(noba, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(transparant1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(email, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(transparant1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(tanggalba, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(transparant1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(totaltunggakan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(transparant1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tahapcicilan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(transparant1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(hnotifikasi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(44, 44, 44))
        );

        transparant2.setBackground(new java.awt.Color(41, 22, 111));
        transparant2.setForeground(new java.awt.Color(41, 22, 111));
        transparant2.setToolTipText("");

        tableba.setAutoCreateRowSorter(true);
        tableba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableba.setColumnSelectionAllowed(true);
        tableba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablebaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableba);
        tableba.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        paginba.setBackground(new java.awt.Color(255, 255, 255));
        paginba.setForeground(new java.awt.Color(0, 0, 51));
        paginba.addPaginationListener(new com.stripbandunk.jwidget.listener.PaginationListener() {
            public void onPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {
                paginbaOnPageChange(evt);
            }
        });

        cariba.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cariba.setForeground(new java.awt.Color(0, 0, 51));
        cariba.setBorder(null);
        cariba.setCaretColor(new java.awt.Color(0, 0, 51));

        btncari.setText("FILTER");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        tombolimport.setText("IMPORT EXCEL");
        tombolimport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolimportActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout transparant2Layout = new org.jdesktop.layout.GroupLayout(transparant2);
        transparant2.setLayout(transparant2Layout);
        transparant2Layout.setHorizontalGroup(
            transparant2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(transparant2Layout.createSequentialGroup()
                .addContainerGap()
                .add(transparant2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, transparant2Layout.createSequentialGroup()
                        .add(tombolimport, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 302, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(paginba, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(transparant2Layout.createSequentialGroup()
                        .add(transparant2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(transparant2Layout.createSequentialGroup()
                                .add(kategori, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cariba, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(btncari, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        transparant2Layout.setVerticalGroup(
            transparant2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(transparant2Layout.createSequentialGroup()
                .addContainerGap()
                .add(transparant2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cariba, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(kategori, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26)
                .add(btncari, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(transparant2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(paginba, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(tombolimport, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(29, 29, 29))
        );

        baru.setText("BARU");
        baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruActionPerformed(evt);
            }
        });

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        update.setText("UBAH");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("HAPUS");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout deskPanelDasar1Layout = new org.jdesktop.layout.GroupLayout(deskPanelDasar1);
        deskPanelDasar1.setLayout(deskPanelDasar1Layout);
        deskPanelDasar1Layout.setHorizontalGroup(
            deskPanelDasar1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(deskPanelDasar1Layout.createSequentialGroup()
                .addContainerGap()
                .add(deskPanelDasar1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(deskPanelDasar1Layout.createSequentialGroup()
                        .add(baru, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(simpan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(update, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(delete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(reset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(transparant1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(deskPanelDasar1Layout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(logoBpjs1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(deskPanelDasar1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(deskPanelDasar1Layout.createSequentialGroup()
                        .add(0, 835, Short.MAX_VALUE)
                        .add(keluar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(transparant2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        deskPanelDasar1Layout.linkSize(new java.awt.Component[] {delete, reset, simpan, update}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        deskPanelDasar1Layout.setVerticalGroup(
            deskPanelDasar1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(deskPanelDasar1Layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(deskPanelDasar1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(logoBpjs1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(keluar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(19, 19, 19)
                .add(deskPanelDasar1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(transparant2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(deskPanelDasar1Layout.createSequentialGroup()
                        .add(transparant1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(deskPanelDasar1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(baru, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(update, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(delete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(reset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(simpan, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(0, 273, Short.MAX_VALUE)))
                .addContainerGap())
        );

        deskPanelDasar1Layout.linkSize(new java.awt.Component[] {baru, delete, reset, simpan, update}, org.jdesktop.layout.GroupLayout.VERTICAL);

        getContentPane().add(deskPanelDasar1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baruActionPerformed(ActionEvent evt) {//GEN-FIRST:event_baruActionPerformed
       c.reset(this);
       c.setenable(this, true);
    }//GEN-LAST:event_baruActionPerformed

    private void simpanActionPerformed(ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        c.simpan(this, this);
        c.reset(this);
        c.setenable(this, false);
    }//GEN-LAST:event_simpanActionPerformed

    private void updateActionPerformed(ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        c.update(this, this);
        c.reset(this);
        c.setenable(this, false);
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        c.hapus(this, this);
        c.reset(this);
        c.setenable(this, false);
    }//GEN-LAST:event_deleteActionPerformed

    private void resetActionPerformed(ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        c.reset(this);
    }//GEN-LAST:event_resetActionPerformed

    private void formWindowOpened(WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       c.LoadAllBA(this, null, null, null);
       c.setenable(this, false);
    }//GEN-LAST:event_formWindowOpened

    private void btncariActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        c.LoadSearch(this, this);
    }//GEN-LAST:event_btncariActionPerformed

    private void paginbaOnPageChange(PaginationEvent evt) {//GEN-FIRST:event_paginbaOnPageChange
        int a = evt.getCurrentPage();
        c.actionPagination(this, a-1);
    }//GEN-LAST:event_paginbaOnPageChange

    private void tablebaMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tablebaMouseClicked
        c.klik(this, evt);
        c.setenable(this, true);
    }//GEN-LAST:event_tablebaMouseClicked

    private void keluarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
       dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void namabuActionPerformed(ActionEvent evt) {//GEN-FIRST:event_namabuActionPerformed
        noentitas.requestFocus();
    }//GEN-LAST:event_namabuActionPerformed

    private void noentitasActionPerformed(ActionEvent evt) {//GEN-FIRST:event_noentitasActionPerformed
       noba.requestFocus();
    }//GEN-LAST:event_noentitasActionPerformed

    private void nobaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_nobaActionPerformed
       email.requestFocus();
    }//GEN-LAST:event_nobaActionPerformed

    private void emailActionPerformed(ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
       totaltunggakan.requestFocus();
    }//GEN-LAST:event_emailActionPerformed

    private void totaltunggakanActionPerformed(ActionEvent evt) {//GEN-FIRST:event_totaltunggakanActionPerformed
        tahapcicilan.requestFocus();
    }//GEN-LAST:event_totaltunggakanActionPerformed

    private void tahapcicilanActionPerformed(ActionEvent evt) {//GEN-FIRST:event_tahapcicilanActionPerformed
        hnotifikasi.requestFocus();
    }//GEN-LAST:event_tahapcicilanActionPerformed

    private void tombolimportActionPerformed(ActionEvent evt) {//GEN-FIRST:event_tombolimportActionPerformed
       ImportController ic = new ImportController();
       ic.LoadFilechooserBA(this, this);
       c.LoadAllBA(this, null, null, null);
    }//GEN-LAST:event_tombolimportActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baru;
    private javax.swing.JButton btncari;
    private javax.swing.JTextField cariba;
    private javax.swing.JButton delete;
    private angsuran.helper.DeskPanelDasar deskPanelDasar1;
    private javax.swing.JTextField email;
    private javax.swing.JTextField hnotifikasi;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JButton keluar;
    private angsuran.helper.LogoBpjs logoBpjs1;
    private javax.swing.JTextField namabu;
    private javax.swing.JTextField noba;
    private javax.swing.JTextField noentitas;
    private com.stripbandunk.jwidget.JPagination paginba;
    private javax.swing.JButton reset;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tableba;
    private javax.swing.JTextField tahapcicilan;
    private com.toedter.calendar.JDateChooser tanggalba;
    private javax.swing.JButton tombolimport;
    private javax.swing.JTextField totaltunggakan;
    private angsuran.helper.Transparant transparant1;
    private angsuran.helper.Transparant transparant2;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Berhasil(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    @Override
    public void Warning(String pesan) {
         JOptionPane.showMessageDialog(this, pesan);
    }

    @Override
    public void Gagal(Throwable t) {
         JOptionPane.showMessageDialog(this, t.getMessage());
    }
}
