/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package angsuran.view;

import angsuran.controller.CicilanController;
import angsuran.helper.HelperUmum;
import angsuran.helper.TombolCrud;
import angsuran.helper.TombolGeneral;
import angsuran.listener.Confirm;
import angsuran.model.Ba;
import angsuran.model.Cicilan;
import com.toedter.calendar.JDateChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class CicilanFrame extends javax.swing.JFrame implements Confirm{

    /**
     * Creates new form CicilanFrame
     */
    private Cicilan cicilan = new Cicilan();

    public Cicilan getCicilan() {
        return cicilan;
    }

    public void setCicilan(Cicilan cicilan) {
        this.cicilan = cicilan;
    }
    
    //=======================================
    private Ba ba = new Ba();

    public Ba getBa() {
        return ba;
    }

    public void setBa(Ba ba) {
        this.ba = ba;
    }
    //=======================================

    public JTextField getKodecicilan() {
        return kodecicilan;
    }

    public JTable getTablecicilan() {
        return tablecicilan;
    }
    

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }


    public JTextField getKekurangancicilan() {
        return kekurangancicilan;
    }

    public JTextField getNamaba() {
        return namaba;
    }

    public JTextField getNoba() {
        return noba;
    }

    public JTextField getNominalcicilan() {
        return nominalcicilan;
    }

    public JTextField getStatuscicilan() {
        return statuscicilan;
    }

    public JTextField getTagihanberjalan() {
        return tagihanberjalan;
    }

    public JDateChooser getTanggalcicilan() {
        return tanggalcicilan;
    }

    public JTextField getTotalcicilan() {
        return totalcicilan;
    }

    public JTextField getTotaltunggakan() {
        return totaltunggakan;
    }

    public JTextField getTahapancicilan() {
        return tahapancicilan;
    }

    public JDateChooser getTanggalnotifikasi() {
        return tanggalnotifikasi;
    }
    
    
    
    private CicilanController c;
    
    public CicilanFrame() {
        initComponents();
        HelperUmum.formatInputanTextfield(nominalcicilan);
        HelperUmum.setTextfieldHanyaAngka(nominalcicilan);
        HelperUmum.formatInputanTextfield(tagihanberjalan);
        HelperUmum.setTextfieldHanyaAngka(tagihanberjalan);
        HelperUmum.setTextfieldHanyaAngka(tahapancicilan);
        new TombolCrud(baru);
        new TombolCrud(simpan);
        new TombolCrud(ubah);
        new TombolCrud(hapus);
        new TombolCrud(reset);
        new TombolCrud(newba);
        new TombolGeneral(keluar);
        HelperUmum.setUpResolution(this);
        HelperUmum.setlogoframe(this);
        c = new CicilanController();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPanelDasar1 = new angsuran.helper.DeskPanelDasar();
        logoBpjs1 = new angsuran.helper.LogoBpjs();
        transparant1 = new angsuran.helper.Transparant();
        jLabel10 = new javax.swing.JLabel();
        nominalcicilan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tagihanberjalan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        totalcicilan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        kekurangancicilan = new javax.swing.JTextField();
        tanggalcicilan = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        statuscicilan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        kodecicilan = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tahapancicilan = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tanggalnotifikasi = new com.toedter.calendar.JDateChooser();
        transparant2 = new angsuran.helper.Transparant();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecicilan = new javax.swing.JTable();
        transparant3 = new angsuran.helper.Transparant();
        jLabel6 = new javax.swing.JLabel();
        noba = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        namaba = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totaltunggakan = new javax.swing.JTextField();
        newba = new javax.swing.JButton();
        baru = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout logoBpjs1Layout = new javax.swing.GroupLayout(logoBpjs1);
        logoBpjs1.setLayout(logoBpjs1Layout);
        logoBpjs1Layout.setHorizontalGroup(
            logoBpjs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        logoBpjs1Layout.setVerticalGroup(
            logoBpjs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel10.setBackground(new java.awt.Color(0, 0, 51));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Nominal Cicilan");

        nominalcicilan.setBackground(new java.awt.Color(255, 255, 255));
        nominalcicilan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        nominalcicilan.setForeground(new java.awt.Color(0, 0, 51));
        nominalcicilan.setBorder(null);
        nominalcicilan.setCaretColor(new java.awt.Color(0, 0, 51));
        nominalcicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nominalcicilanActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 0, 51));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Tagihan Berjalan");

        tagihanberjalan.setBackground(new java.awt.Color(255, 255, 255));
        tagihanberjalan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        tagihanberjalan.setForeground(new java.awt.Color(0, 0, 51));
        tagihanberjalan.setBorder(null);
        tagihanberjalan.setCaretColor(new java.awt.Color(0, 0, 51));
        tagihanberjalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagihanberjalanActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 0, 51));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("Total cicilan");

        totalcicilan.setEditable(false);
        totalcicilan.setBackground(new java.awt.Color(255, 204, 0));
        totalcicilan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        totalcicilan.setForeground(new java.awt.Color(0, 0, 51));
        totalcicilan.setBorder(null);
        totalcicilan.setCaretColor(new java.awt.Color(0, 0, 51));

        jLabel13.setBackground(new java.awt.Color(0, 0, 51));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("Kekurangan");

        kekurangancicilan.setEditable(false);
        kekurangancicilan.setBackground(new java.awt.Color(255, 204, 0));
        kekurangancicilan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        kekurangancicilan.setForeground(new java.awt.Color(0, 0, 51));
        kekurangancicilan.setBorder(null);
        kekurangancicilan.setCaretColor(new java.awt.Color(0, 0, 51));

        tanggalcicilan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalcicilanPropertyChange(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 51));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setText("Jatuh Tempo");

        jLabel15.setBackground(new java.awt.Color(0, 0, 51));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("Status Cicilan");

        statuscicilan.setEditable(false);
        statuscicilan.setBackground(new java.awt.Color(255, 204, 0));
        statuscicilan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        statuscicilan.setForeground(new java.awt.Color(0, 0, 51));
        statuscicilan.setBorder(null);
        statuscicilan.setCaretColor(new java.awt.Color(0, 0, 51));

        jLabel16.setBackground(new java.awt.Color(0, 0, 51));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 51));
        jLabel16.setText("Kode Cicilan");

        kodecicilan.setEditable(false);
        kodecicilan.setBackground(new java.awt.Color(255, 204, 0));
        kodecicilan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        kodecicilan.setForeground(new java.awt.Color(0, 0, 51));
        kodecicilan.setBorder(null);
        kodecicilan.setCaretColor(new java.awt.Color(0, 0, 51));

        jLabel17.setBackground(new java.awt.Color(0, 0, 51));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 51));
        jLabel17.setText("Tahapan Cicilan");

        tahapancicilan.setBackground(new java.awt.Color(255, 255, 255));
        tahapancicilan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        tahapancicilan.setForeground(new java.awt.Color(0, 0, 51));
        tahapancicilan.setBorder(null);
        tahapancicilan.setCaretColor(new java.awt.Color(0, 0, 51));
        tahapancicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahapancicilanActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(0, 0, 51));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setText("Tanggal Notifikasi");

        javax.swing.GroupLayout transparant1Layout = new javax.swing.GroupLayout(transparant1);
        transparant1.setLayout(transparant1Layout);
        transparant1Layout.setHorizontalGroup(
            transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tanggalcicilan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kekurangancicilan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statuscicilan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nominalcicilan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagihanberjalan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalcicilan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodecicilan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahapancicilan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalnotifikasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transparant1Layout.setVerticalGroup(
            transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tanggalcicilan, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tanggalnotifikasi, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodecicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(transparant1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(tahapancicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transparant1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nominalcicilan, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tagihanberjalan, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalcicilan, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kekurangancicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(transparant1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)))
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transparant1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(statuscicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablecicilan.setAutoCreateRowSorter(true);
        tablecicilan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablecicilan.setColumnSelectionAllowed(true);
        tablecicilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecicilanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablecicilan);
        tablecicilan.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout transparant2Layout = new javax.swing.GroupLayout(transparant2);
        transparant2.setLayout(transparant2Layout);
        transparant2Layout.setHorizontalGroup(
            transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
                .addContainerGap())
        );
        transparant2Layout.setVerticalGroup(
            transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setBackground(new java.awt.Color(0, 0, 51));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("No Entitas");

        noba.setBackground(new java.awt.Color(255, 255, 255));
        noba.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        noba.setForeground(new java.awt.Color(0, 0, 51));
        noba.setBorder(null);
        noba.setCaretColor(new java.awt.Color(0, 0, 51));
        noba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nobaActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 51));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Nama BA");

        namaba.setEditable(false);
        namaba.setBackground(new java.awt.Color(255, 204, 0));
        namaba.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        namaba.setForeground(new java.awt.Color(0, 0, 51));
        namaba.setBorder(null);
        namaba.setCaretColor(new java.awt.Color(0, 0, 51));

        jLabel8.setBackground(new java.awt.Color(0, 0, 51));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Total Tunggakan");

        totaltunggakan.setEditable(false);
        totaltunggakan.setBackground(new java.awt.Color(255, 204, 0));
        totaltunggakan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        totaltunggakan.setForeground(new java.awt.Color(0, 0, 51));
        totaltunggakan.setBorder(null);
        totaltunggakan.setCaretColor(new java.awt.Color(0, 0, 51));

        newba.setBackground(new java.awt.Color(0, 153, 0));
        newba.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        newba.setText("NEW BA");
        newba.setBorder(null);
        newba.setBorderPainted(false);
        newba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transparant3Layout = new javax.swing.GroupLayout(transparant3);
        transparant3.setLayout(transparant3Layout);
        transparant3Layout.setHorizontalGroup(
            transparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(transparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totaltunggakan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newba, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        transparant3Layout.setVerticalGroup(
            transparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(noba, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(newba, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaba, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaltunggakan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        baru.setBackground(new java.awt.Color(0, 153, 0));
        baru.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        baru.setText("BARU");
        baru.setBorder(null);
        baru.setBorderPainted(false);
        baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruActionPerformed(evt);
            }
        });

        simpan.setBackground(new java.awt.Color(0, 153, 0));
        simpan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        simpan.setText("SIMPAN");
        simpan.setBorder(null);
        simpan.setBorderPainted(false);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        ubah.setBackground(new java.awt.Color(0, 153, 0));
        ubah.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        ubah.setText("UBAH");
        ubah.setBorder(null);
        ubah.setBorderPainted(false);
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(0, 153, 0));
        hapus.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        hapus.setText("HAPUS");
        hapus.setBorder(null);
        hapus.setBorderPainted(false);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(0, 153, 0));
        reset.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        reset.setText("RESET");
        reset.setBorder(null);
        reset.setBorderPainted(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deskPanelDasar1Layout = new javax.swing.GroupLayout(deskPanelDasar1);
        deskPanelDasar1.setLayout(deskPanelDasar1Layout);
        deskPanelDasar1Layout.setHorizontalGroup(
            deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                        .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                                .addComponent(baru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                                .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(transparant3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(transparant1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(transparant2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                        .addComponent(logoBpjs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        deskPanelDasar1Layout.setVerticalGroup(
            deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoBpjs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                        .addComponent(transparant3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transparant1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(transparant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(baru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(deskPanelDasar1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruActionPerformed
        c.EnableCicilan(this, true);
        c.ResetCicilan(this);
    }//GEN-LAST:event_baruActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
       c.simpan(this, this);
       c.ResetCicilan(this);
       c.EnableCicilan(this, false);
       c.loadcicilan(this, ba);
    }//GEN-LAST:event_simpanActionPerformed

    private void nobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nobaActionPerformed
       c.findba(this, this, noba.getText());
       tahapancicilan.requestFocus();
    }//GEN-LAST:event_nobaActionPerformed

    private void newbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbaActionPerformed
       c.ResetBa(this);
    }//GEN-LAST:event_newbaActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
       c.ubah(this, this);
       c.ResetCicilan(this);
       c.EnableCicilan(this, false);
       c.loadcicilan(this, ba);
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
       c.hapus(this, this);
       c.ResetCicilan(this);
       c.EnableCicilan(this, false);
       c.loadcicilan(this, ba);
    }//GEN-LAST:event_hapusActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       c.ResetCicilan(this);
    }//GEN-LAST:event_resetActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void tablecicilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecicilanMouseClicked
       c.LoadKlik(this, evt);
       c.EnableCicilan(this, Boolean.TRUE);
    }//GEN-LAST:event_tablecicilanMouseClicked

    private void tagihanberjalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagihanberjalanActionPerformed
        c.jumlahnominaltagihan(this, this);
    }//GEN-LAST:event_tagihanberjalanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        c.EnableCicilan(this, false);
    }//GEN-LAST:event_formWindowOpened

    private void tanggalcicilanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalcicilanPropertyChange
     
    }//GEN-LAST:event_tanggalcicilanPropertyChange

    private void tahapancicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahapancicilanActionPerformed
       nominalcicilan.requestFocus();
    }//GEN-LAST:event_tahapancicilanActionPerformed

    private void nominalcicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nominalcicilanActionPerformed
        tagihanberjalan.requestFocus();
    }//GEN-LAST:event_nominalcicilanActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baru;
    private angsuran.helper.DeskPanelDasar deskPanelDasar1;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kekurangancicilan;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kodecicilan;
    private angsuran.helper.LogoBpjs logoBpjs1;
    private javax.swing.JTextField namaba;
    private javax.swing.JButton newba;
    private javax.swing.JTextField noba;
    private javax.swing.JTextField nominalcicilan;
    private javax.swing.JButton reset;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField statuscicilan;
    private javax.swing.JTable tablecicilan;
    private javax.swing.JTextField tagihanberjalan;
    private javax.swing.JTextField tahapancicilan;
    private com.toedter.calendar.JDateChooser tanggalcicilan;
    private com.toedter.calendar.JDateChooser tanggalnotifikasi;
    private javax.swing.JTextField totalcicilan;
    private javax.swing.JTextField totaltunggakan;
    private angsuran.helper.Transparant transparant1;
    private angsuran.helper.Transparant transparant2;
    private angsuran.helper.Transparant transparant3;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Berhasil(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    @Override
    public void Warning(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    @Override
    public void Gagal(Throwable t) {
       JOptionPane.showMessageDialog(this, t.getMessage());
    }
}
