/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package angsuran.view;

import angsuran.controller.MenuUtamaController;
import angsuran.helper.HelperUmum;
import angsuran.helper.TombolCrud;
import angsuran.helper.TombolGeneral;
import angsuran.listener.Confirm;
import angsuran.model.UserModel;
import com.stripbandunk.jwidget.JPagination;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author User
 */
public final class MenuUtama extends javax.swing.JFrame implements Confirm{
    
    private UserModel model = new UserModel();

    public UserModel getModel() {
        return model;
    }

    public void setModel(UserModel model) {
        this.model = model;
    }
    
    //==========================================================================

    public JButton getBa() {
        return ba;
    }

    public JButton getCicilan() {
        return cicilan;
    }

    public JButton getPembayaran() {
        return pembayaran;
    }

    public JButton getPrint() {
        return notifikasi;
    }
    
    public JButton getUser() {
        return managementuser;
    }

    public JButton getManagementsmtp() {
        return managementsmtp;
    }

    public JButton getLaporan() {
        return laporan;
    }
    
      
    //===========================

    public JPagination getPagination() {
        return Pagination;
    }

    public JTable getTableFilter() {
        return TableFilter;
    }
    
    
    
    //===========================
    
    private TombolGeneral tombolGeneral;
    private TombolCrud crud;
    
    private MenuUtamaController cc = new MenuUtamaController();
   
    public MenuUtama(){
        initComponents();
         tombolGeneral = new TombolGeneral(ba);
         tombolGeneral = new TombolGeneral(cicilan);
         tombolGeneral = new TombolGeneral(managementuser);
         tombolGeneral = new TombolGeneral(pembayaran);
         tombolGeneral = new TombolGeneral(managementsmtp);
         tombolGeneral = new TombolGeneral(laporan);
         crud = new TombolCrud(refresh);
         crud = new TombolCrud(lihatnotifikasi);
         HelperUmum.setUpResolution(this);     
         HelperUmum.setlogoframe(this);
         cc.LoadAllFilter(this);
         //LoadReport();
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPanelDasar1 = new angsuran.helper.DeskPanelDasar();
        logoBpjs1 = new angsuran.helper.LogoBpjs();
        transparant2 = new angsuran.helper.Transparant();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableFilter = new javax.swing.JTable();
        Pagination = new com.stripbandunk.jwidget.JPagination();
        refresh = new javax.swing.JButton();
        lihatnotifikasi = new javax.swing.JButton();
        transparant3 = new angsuran.helper.Transparant();
        ba = new javax.swing.JButton();
        cicilan = new javax.swing.JButton();
        pembayaran = new javax.swing.JButton();
        managementuser = new javax.swing.JButton();
        managementsmtp = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        notifikasi = new javax.swing.JButton();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout logoBpjs1Layout = new javax.swing.GroupLayout(logoBpjs1);
        logoBpjs1.setLayout(logoBpjs1Layout);
        logoBpjs1Layout.setHorizontalGroup(
            logoBpjs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        logoBpjs1Layout.setVerticalGroup(
            logoBpjs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        TableFilter.setAutoCreateRowSorter(true);
        TableFilter.setBackground(new java.awt.Color(255, 255, 255));
        TableFilter.setForeground(new java.awt.Color(0, 0, 0));
        TableFilter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TableFilter.setColumnSelectionAllowed(true);
        TableFilter.setGridColor(new java.awt.Color(0, 153, 51));
        jScrollPane1.setViewportView(TableFilter);
        TableFilter.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        Pagination.addPaginationListener(new com.stripbandunk.jwidget.listener.PaginationListener() {
            public void onPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {
                PaginationOnPageChange(evt);
            }
        });

        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        lihatnotifikasi.setText("LIHAT NOTIFIKASI");
        lihatnotifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatnotifikasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transparant2Layout = new javax.swing.GroupLayout(transparant2);
        transparant2.setLayout(transparant2Layout);
        transparant2Layout.setHorizontalGroup(
            transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                    .addGroup(transparant2Layout.createSequentialGroup()
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lihatnotifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pagination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        transparant2Layout.setVerticalGroup(
            transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transparant2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Pagination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lihatnotifikasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ba.setBackground(new java.awt.Color(14, 14, 67));
        ba.setForeground(new java.awt.Color(255, 255, 255));
        ba.setText("MANAGEMENT BA");
        ba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baActionPerformed(evt);
            }
        });

        cicilan.setText("MANAGEMENT CICILAN");
        cicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cicilanActionPerformed(evt);
            }
        });

        pembayaran.setText("OLAH PEMBAYARAN");
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });

        managementuser.setText("MANAGEMENT USER");
        managementuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementuserActionPerformed(evt);
            }
        });

        managementsmtp.setText("MANAGEMENT SMTP");
        managementsmtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementsmtpActionPerformed(evt);
            }
        });

        laporan.setText("LAPORAN ");
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transparant3Layout = new javax.swing.GroupLayout(transparant3);
        transparant3.setLayout(transparant3Layout);
        transparant3Layout.setHorizontalGroup(
            transparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cicilan, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(managementuser, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(managementsmtp, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(laporan, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addContainerGap())
        );
        transparant3Layout.setVerticalGroup(
            transparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ba, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(managementuser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(managementsmtp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        notifikasi.setBackground(new java.awt.Color(0, 153, 51));
        notifikasi.setForeground(new java.awt.Color(255, 255, 255));
        notifikasi.setText("CHECK PENGIRIMAN NOTIFIKASI");
        notifikasi.setBorder(null);
        notifikasi.setBorderPainted(false);
        notifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifikasiActionPerformed(evt);
            }
        });

        print.setBackground(new java.awt.Color(0, 153, 51));
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("PRINT");
        print.setBorder(null);
        print.setBorderPainted(false);
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deskPanelDasar1Layout = new javax.swing.GroupLayout(deskPanelDasar1);
        deskPanelDasar1.setLayout(deskPanelDasar1Layout);
        deskPanelDasar1Layout.setHorizontalGroup(
            deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                        .addComponent(transparant3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(transparant2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                        .addComponent(logoBpjs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245)
                        .addComponent(notifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        deskPanelDasar1Layout.setVerticalGroup(
            deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoBpjs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(notifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(transparant2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transparant3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(deskPanelDasar1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baActionPerformed
        BAFrame f = new BAFrame();
        f.setTitle("Management BA");
        f.setVisible(true);
    }//GEN-LAST:event_baActionPerformed

    private void cicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cicilanActionPerformed
        CicilanFrame cf = new CicilanFrame();
        cf.setTitle("Management Cicilan");
        cf.setVisible(true);
    }//GEN-LAST:event_cicilanActionPerformed

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        PembayaranFrame ff = new PembayaranFrame();
        ff.setTitle("Management Pmbayaran Cicilan");
        ff.setVisible(true);
    }//GEN-LAST:event_pembayaranActionPerformed

    private void managementuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementuserActionPerformed
        UserFrame fd = new UserFrame();
        fd.setTitle("Management User");
        fd.setVisible(true);
    }//GEN-LAST:event_managementuserActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          cc.tampil(this, this);
    }//GEN-LAST:event_formWindowOpened

    private void notifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifikasiActionPerformed
          cc.LoadReport(this, this);    
    }//GEN-LAST:event_notifikasiActionPerformed

    private void PaginationOnPageChange(com.stripbandunk.jwidget.event.PaginationEvent evt) {//GEN-FIRST:event_PaginationOnPageChange
        int a = evt.getCurrentPage();
        cc.actionPagination(this, a-1);
    }//GEN-LAST:event_PaginationOnPageChange

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            cc.createreport(this, this);
        } catch (JRException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
       cc.LoadAllFilter(this);
    }//GEN-LAST:event_refreshActionPerformed

    private void lihatnotifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatnotifikasiActionPerformed
        NotifikasiFrame f = new NotifikasiFrame();
        f.setVisible(true);
    }//GEN-LAST:event_lihatnotifikasiActionPerformed

    private void managementsmtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementsmtpActionPerformed
        SmtpFrame f = new SmtpFrame();
        f.setTitle("MANAGEMENT SMTP");
        f.setVisible(true);
    }//GEN-LAST:event_managementsmtpActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        LaporanFrame dfg = new LaporanFrame();
        dfg.setTitle("MANAGEMENT LAPORAN");
        dfg.setVisible(true);
    }//GEN-LAST:event_laporanActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.stripbandunk.jwidget.JPagination Pagination;
    private javax.swing.JTable TableFilter;
    private javax.swing.JButton ba;
    private javax.swing.JButton cicilan;
    private angsuran.helper.DeskPanelDasar deskPanelDasar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton laporan;
    private javax.swing.JButton lihatnotifikasi;
    private angsuran.helper.LogoBpjs logoBpjs1;
    private javax.swing.JButton managementsmtp;
    private javax.swing.JButton managementuser;
    private javax.swing.JButton notifikasi;
    private javax.swing.JButton pembayaran;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private angsuran.helper.Transparant transparant2;
    private angsuran.helper.Transparant transparant3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Berhasil(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    @Override
    public void Warning(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    @Override
    public void Gagal(Throwable t) {
        JOptionPane.showMessageDialog(this, t.getMessage());
    }
}
