/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package angsuran.view;

import angsuran.controller.PembayaranController;
import angsuran.helper.HelperUmum;
import angsuran.helper.TombolCrud;
import angsuran.helper.TombolGeneral;
import angsuran.listener.Confirm;
import angsuran.model.Cicilan;
import angsuran.model.Pembayaran;
import com.toedter.calendar.JDateChooser;
import java.awt.event.ItemEvent;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class PembayaranFrame extends javax.swing.JFrame implements Confirm{
    
    private Pembayaran pembayaran = new Pembayaran();
    private JFrame jfm;

    public Pembayaran getPembayaran() {
        return pembayaran;
    }

    public void setPembayaran(Pembayaran pembayaran) {
        this.pembayaran = pembayaran;
    }
    
    //==========================================================================
    
    private Cicilan cicilan = new Cicilan();

    public Cicilan getCicilan() {
        return cicilan;
    }

    public void setCicilan(Cicilan cicilan) {
        this.cicilan = cicilan;
    }
    
    //==========================================================================

    public JTextField getCariba() {
        return cariba;
    }

    public JList<String> getListba() {
        return listba;
    }

    public JFrame getFrameCicilan() {
        return FrameCicilan;
    }

    public JComboBox<String> getKategori() {
        return kategori;
    }

    public JTable getTabelcicilan() {
        return tabelcicilan;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTextField getKodecicilan() {
        return kodecicilan;
    }

    public JTable getTablepembayaran() {
        return tablepembayaran;
    }

    public JDateChooser getTanggal() {
        return tanggal;
    }

    public JTextField getTotal() {
        return total;
    }

    public JTextField getTotalcicilan() {
        return totalcicilan;
    }

    public JTextField getTotalkekurangan() {
        return totalkekurangan;
    }

    public JTextField getTotalpembayaran() {
        return totalpembayaran;
    }

    public JTextField getTotaltunggakan() {
        return totaltunggakan;
    }

    public JTextField getPembayarancicilan() {
        return pembayarancicilan;
    }

    public JTextField getPembayarantunggakan() {
        return pembayarantunggakan;
    }

    public JTextField getSubtotal() {
        return subtotal;
    }

    private PembayaranController c;

    public PembayaranFrame() {
        initComponents();
        jfm = this.FrameCicilan;
        new TombolCrud(baru);
        new TombolCrud(simpan);
        new TombolCrud(hapus);
        new TombolCrud(reset);
        new TombolCrud(newcicilan);
        new TombolCrud(caricicilan);
        new TombolGeneral(keluar);
        HelperUmum.setUpResolution(this);
        HelperUmum.setlogoframe(this);
        //=========================================
        HelperUmum.setTextfieldHanyaAngka(pembayarancicilan);
        HelperUmum.formatInputanTextfield(pembayarancicilan);
        HelperUmum.setTextfieldHanyaAngka(pembayarantunggakan);
        HelperUmum.formatInputanTextfield(pembayarantunggakan);
        c = new PembayaranController();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameCicilan = new javax.swing.JFrame();
        deskPanelDasar2 = new angsuran.helper.DeskPanelDasar();
        logoBpjs2 = new angsuran.helper.LogoBpjs();
        transparant1 = new angsuran.helper.Transparant();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelcicilan = new javax.swing.JTable();
        cariba = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        kategori = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listba = new javax.swing.JList<>();
        deskPanelDasar1 = new angsuran.helper.DeskPanelDasar();
        logoBpjs1 = new angsuran.helper.LogoBpjs();
        transparant2 = new angsuran.helper.Transparant();
        jLabel10 = new javax.swing.JLabel();
        pembayarantunggakan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pembayarancicilan = new javax.swing.JTextField();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        transparant3 = new angsuran.helper.Transparant();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepembayaran = new javax.swing.JTable();
        transparant4 = new angsuran.helper.Transparant();
        jLabel6 = new javax.swing.JLabel();
        kodecicilan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        totalcicilan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totaltunggakan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalkekurangan = new javax.swing.JTextField();
        newcicilan = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        totalpembayaran = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();
        caricicilan = new javax.swing.JButton();
        baru = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        FrameCicilan.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                FrameCicilanWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout logoBpjs2Layout = new javax.swing.GroupLayout(logoBpjs2);
        logoBpjs2.setLayout(logoBpjs2Layout);
        logoBpjs2Layout.setHorizontalGroup(
            logoBpjs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );
        logoBpjs2Layout.setVerticalGroup(
            logoBpjs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        transparant1.setBackground(new java.awt.Color(41, 22, 111));
        transparant1.setForeground(new java.awt.Color(41, 22, 111));
        transparant1.setToolTipText("");

        tabelcicilan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelcicilan.setColumnSelectionAllowed(true);
        tabelcicilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelcicilanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelcicilan);
        tabelcicilan.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        cariba.setBackground(new java.awt.Color(255, 255, 255));
        cariba.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cariba.setForeground(new java.awt.Color(0, 0, 51));
        cariba.setBorder(null);
        cariba.setCaretColor(new java.awt.Color(0, 0, 51));
        cariba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caribaActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(0, 0, 51));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 51));
        jLabel17.setText("KEY SEARCH");

        kategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kategoriItemStateChanged(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(0, 0, 51));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setText("KATEGORI");

        listba.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listbaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listba);

        javax.swing.GroupLayout transparant1Layout = new javax.swing.GroupLayout(transparant1);
        transparant1.setLayout(transparant1Layout);
        transparant1Layout.setHorizontalGroup(
            transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transparant1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transparant1Layout.createSequentialGroup()
                        .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kategori, javax.swing.GroupLayout.Alignment.TRAILING, 0, 211, Short.MAX_VALUE)
                            .addComponent(cariba, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                .addContainerGap())
        );

        transparant1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel17, jLabel18});

        transparant1Layout.setVerticalGroup(
            transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariba, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );

        transparant1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cariba, kategori});

        transparant1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel17, jLabel18});

        javax.swing.GroupLayout deskPanelDasar2Layout = new javax.swing.GroupLayout(deskPanelDasar2);
        deskPanelDasar2.setLayout(deskPanelDasar2Layout);
        deskPanelDasar2Layout.setHorizontalGroup(
            deskPanelDasar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPanelDasar2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deskPanelDasar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transparant1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(deskPanelDasar2Layout.createSequentialGroup()
                        .addComponent(logoBpjs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        deskPanelDasar2Layout.setVerticalGroup(
            deskPanelDasar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPanelDasar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoBpjs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(transparant1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        FrameCicilan.getContentPane().add(deskPanelDasar2, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout logoBpjs1Layout = new javax.swing.GroupLayout(logoBpjs1);
        logoBpjs1.setLayout(logoBpjs1Layout);
        logoBpjs1Layout.setHorizontalGroup(
            logoBpjs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        logoBpjs1Layout.setVerticalGroup(
            logoBpjs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        transparant2.setBackground(new java.awt.Color(41, 22, 111));
        transparant2.setForeground(new java.awt.Color(41, 22, 111));
        transparant2.setToolTipText("");

        jLabel10.setBackground(new java.awt.Color(0, 0, 51));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("Tanggal");

        pembayarantunggakan.setBackground(new java.awt.Color(255, 255, 255));
        pembayarantunggakan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        pembayarantunggakan.setForeground(new java.awt.Color(0, 0, 51));
        pembayarantunggakan.setBorder(null);
        pembayarantunggakan.setCaretColor(new java.awt.Color(0, 0, 51));
        pembayarantunggakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayarantunggakanActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 0, 51));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("Pembayaran Cicilan");

        total.setEditable(false);
        total.setBackground(new java.awt.Color(255, 204, 0));
        total.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 51));
        total.setBorder(null);
        total.setCaretColor(new java.awt.Color(0, 0, 51));

        jLabel12.setBackground(new java.awt.Color(0, 0, 51));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("Total");

        pembayarancicilan.setBackground(new java.awt.Color(255, 255, 255));
        pembayarancicilan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        pembayarancicilan.setForeground(new java.awt.Color(0, 0, 51));
        pembayarancicilan.setBorder(null);
        pembayarancicilan.setCaretColor(new java.awt.Color(0, 0, 51));
        pembayarancicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayarancicilanActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(0, 0, 51));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("Pembayaran Bulan Berjalan");

        javax.swing.GroupLayout transparant2Layout = new javax.swing.GroupLayout(transparant2);
        transparant2.setLayout(transparant2Layout);
        transparant2Layout.setHorizontalGroup(
            transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transparant2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(transparant2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transparant2Layout.createSequentialGroup()
                        .addGroup(transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pembayarantunggakan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pembayarancicilan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(79, 79, 79))
        );
        transparant2Layout.setVerticalGroup(
            transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pembayarancicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pembayarantunggakan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        transparant3.setBackground(new java.awt.Color(41, 22, 111));
        transparant3.setForeground(new java.awt.Color(41, 22, 111));
        transparant3.setToolTipText("");

        tablepembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablepembayaran.setColumnSelectionAllowed(true);
        tablepembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablepembayaran);
        tablepembayaran.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout transparant3Layout = new javax.swing.GroupLayout(transparant3);
        transparant3.setLayout(transparant3Layout);
        transparant3Layout.setHorizontalGroup(
            transparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                .addContainerGap())
        );
        transparant3Layout.setVerticalGroup(
            transparant3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );

        transparant4.setBackground(new java.awt.Color(41, 22, 111));
        transparant4.setForeground(new java.awt.Color(41, 22, 111));
        transparant4.setToolTipText("");

        jLabel6.setBackground(new java.awt.Color(0, 0, 51));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Kode Cicilan");

        kodecicilan.setBackground(new java.awt.Color(255, 255, 255));
        kodecicilan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        kodecicilan.setForeground(new java.awt.Color(0, 0, 51));
        kodecicilan.setBorder(null);
        kodecicilan.setCaretColor(new java.awt.Color(0, 0, 51));
        kodecicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodecicilanActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 51));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Cicilan");

        totalcicilan.setEditable(false);
        totalcicilan.setBackground(new java.awt.Color(255, 204, 0));
        totalcicilan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        totalcicilan.setForeground(new java.awt.Color(0, 0, 51));
        totalcicilan.setBorder(null);
        totalcicilan.setCaretColor(new java.awt.Color(0, 0, 51));

        jLabel8.setBackground(new java.awt.Color(0, 0, 51));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Tunggakan");

        totaltunggakan.setEditable(false);
        totaltunggakan.setBackground(new java.awt.Color(255, 204, 0));
        totaltunggakan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        totaltunggakan.setForeground(new java.awt.Color(0, 0, 51));
        totaltunggakan.setBorder(null);
        totaltunggakan.setCaretColor(new java.awt.Color(0, 0, 51));

        jLabel9.setBackground(new java.awt.Color(0, 0, 51));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Kekurangan");

        totalkekurangan.setEditable(false);
        totalkekurangan.setBackground(new java.awt.Color(255, 204, 0));
        totalkekurangan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        totalkekurangan.setForeground(new java.awt.Color(0, 0, 51));
        totalkekurangan.setBorder(null);
        totalkekurangan.setCaretColor(new java.awt.Color(0, 0, 51));

        newcicilan.setBackground(new java.awt.Color(0, 153, 0));
        newcicilan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        newcicilan.setText("NEW CICILAN");
        newcicilan.setBorder(null);
        newcicilan.setBorderPainted(false);
        newcicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newcicilanActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 51));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setText("Total Pembayaran");

        totalpembayaran.setEditable(false);
        totalpembayaran.setBackground(new java.awt.Color(255, 204, 0));
        totalpembayaran.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        totalpembayaran.setForeground(new java.awt.Color(0, 0, 51));
        totalpembayaran.setBorder(null);
        totalpembayaran.setCaretColor(new java.awt.Color(0, 0, 51));

        jLabel15.setBackground(new java.awt.Color(0, 0, 51));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("Total ");

        subtotal.setEditable(false);
        subtotal.setBackground(new java.awt.Color(255, 204, 0));
        subtotal.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        subtotal.setForeground(new java.awt.Color(0, 0, 51));
        subtotal.setBorder(null);
        subtotal.setCaretColor(new java.awt.Color(0, 0, 51));

        caricicilan.setBackground(new java.awt.Color(0, 153, 0));
        caricicilan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        caricicilan.setText("CARI CICILAN");
        caricicilan.setBorder(null);
        caricicilan.setBorderPainted(false);
        caricicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caricicilanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transparant4Layout = new javax.swing.GroupLayout(transparant4);
        transparant4.setLayout(transparant4Layout);
        transparant4Layout.setHorizontalGroup(
            transparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transparant4Layout.createSequentialGroup()
                        .addGroup(transparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(transparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kodecicilan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totaltunggakan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalcicilan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalpembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(transparant4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalkekurangan, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(transparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newcicilan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caricicilan, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap())
        );
        transparant4Layout.setVerticalGroup(
            transparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparant4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kodecicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(newcicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalcicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(caricicilan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaltunggakan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transparant4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalkekurangan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        baru.setBackground(new java.awt.Color(0, 153, 0));
        baru.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        baru.setText("BARU");
        baru.setBorder(null);
        baru.setBorderPainted(false);
        baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruActionPerformed(evt);
            }
        });

        simpan.setBackground(new java.awt.Color(0, 153, 0));
        simpan.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        simpan.setText("SIMPAN");
        simpan.setBorder(null);
        simpan.setBorderPainted(false);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(0, 153, 0));
        hapus.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        hapus.setText("HAPUS");
        hapus.setBorder(null);
        hapus.setBorderPainted(false);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(0, 153, 0));
        reset.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        reset.setText("RESET");
        reset.setBorder(null);
        reset.setBorderPainted(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deskPanelDasar1Layout = new javax.swing.GroupLayout(deskPanelDasar1);
        deskPanelDasar1.setLayout(deskPanelDasar1Layout);
        deskPanelDasar1Layout.setHorizontalGroup(
            deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                            .addComponent(baru, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(transparant4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(transparant2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(logoBpjs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                        .addGap(0, 830, Short.MAX_VALUE)
                        .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(transparant3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        deskPanelDasar1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {hapus, reset});

        deskPanelDasar1Layout.setVerticalGroup(
            deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoBpjs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deskPanelDasar1Layout.createSequentialGroup()
                        .addComponent(transparant4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transparant2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deskPanelDasar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(baru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(transparant3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        deskPanelDasar1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {baru, hapus, reset, simpan});

        getContentPane().add(deskPanelDasar1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newcicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcicilanActionPerformed

        c.ResetCicilan(this);
    }//GEN-LAST:event_newcicilanActionPerformed

    private void pembayarantunggakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayarantunggakanActionPerformed
        c.settotal(this);
    }//GEN-LAST:event_pembayarantunggakanActionPerformed

    private void kodecicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodecicilanActionPerformed
        c.FindCicilan(this, this, kodecicilan.getText());
        pembayarancicilan.requestFocus();
    }//GEN-LAST:event_kodecicilanActionPerformed

    private void baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruActionPerformed
       c.Enable(this, true);
       c.ResetPembayaran(this);
    }//GEN-LAST:event_baruActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        c.simpan(this, this);
        c.ResetPembayaran(this);
        c.Enable(this, false);
        c.FindCicilan(this, this, kodecicilan.getText());
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        c.delete(this, this);
        c.ResetPembayaran(this);
        c.Enable(this, false);
        c.FindCicilan(this, this, kodecicilan.getText());
    }//GEN-LAST:event_hapusActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        c.ResetPembayaran(this);
    }//GEN-LAST:event_resetActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
       dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void tablepembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepembayaranMouseClicked
        c.klik(this, evt);
    }//GEN-LAST:event_tablepembayaranMouseClicked

    private void pembayarancicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayarancicilanActionPerformed
        pembayarantunggakan.requestFocus();
    }//GEN-LAST:event_pembayarancicilanActionPerformed

    private void caricicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caricicilanActionPerformed
        cariba.setText(null);
        HelperUmum.setUpResolution(jfm);
        HelperUmum.setlogoframe(jfm); 
        c.LoadKategori(this);
        kategori.setSelectedIndex(0);
        jfm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jfm.setVisible(true);
        
    }//GEN-LAST:event_caricicilanActionPerformed

    private void FrameCicilanWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FrameCicilanWindowOpened
        c.LoadKategori(this);
        
    }//GEN-LAST:event_FrameCicilanWindowOpened

    private void caribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caribaActionPerformed
        c.LoadlistBa(this,kategori.getSelectedIndex(),cariba.getText(), this);
    }//GEN-LAST:event_caribaActionPerformed

    private void listbaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listbaMouseClicked
        c.KlikList(this, this);
    }//GEN-LAST:event_listbaMouseClicked

    private void tabelcicilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelcicilanMouseClicked
        c.KlikListcicilan(this, this, evt);
        jfm.setVisible(false);
    }//GEN-LAST:event_tabelcicilanMouseClicked

    private void kategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kategoriItemStateChanged
       if(evt.getStateChange() == ItemEvent.SELECTED){
           c.PilihKategori(this, kategori.getSelectedIndex());
       }
    }//GEN-LAST:event_kategoriItemStateChanged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameCicilan;
    private javax.swing.JButton baru;
    private javax.swing.JTextField cariba;
    private javax.swing.JButton caricicilan;
    private angsuran.helper.DeskPanelDasar deskPanelDasar1;
    private angsuran.helper.DeskPanelDasar deskPanelDasar2;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kodecicilan;
    private javax.swing.JList<String> listba;
    private angsuran.helper.LogoBpjs logoBpjs1;
    private angsuran.helper.LogoBpjs logoBpjs2;
    private javax.swing.JButton newcicilan;
    private javax.swing.JTextField pembayarancicilan;
    private javax.swing.JTextField pembayarantunggakan;
    private javax.swing.JButton reset;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTable tabelcicilan;
    private javax.swing.JTable tablepembayaran;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totalcicilan;
    private javax.swing.JTextField totalkekurangan;
    private javax.swing.JTextField totalpembayaran;
    private javax.swing.JTextField totaltunggakan;
    private angsuran.helper.Transparant transparant1;
    private angsuran.helper.Transparant transparant2;
    private angsuran.helper.Transparant transparant3;
    private angsuran.helper.Transparant transparant4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Berhasil(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    @Override
    public void Warning(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }

    @Override
    public void Gagal(Throwable t) {
        JOptionPane.showMessageDialog(this, t.getMessage());
    }
}
